### ISSUE TITLE
Aggregate

### ISSUE THREAD

**Issue by CFYanarella** [Dill-PICL/GOMAP-singularity#11]
**Describe the bug**
I removed the tabs from the description, reran the fanngo step, and aggregate still failed.

**Input File**
```
>HORVU1Hr1G000010.3 HORVU1Hr1G000010|chr1H:41961-45310|HC_G|RING-H2 finger protein 2B|GO:0005515, GO:0008270|PF13639|IPR001841, IPR013083
VGLLSLSRLHPNHNPNPNPNPNRLRSVCPPHPSIRPPSQTLDWSGAEATDAGAAAAAAAA
GALRRQPPVPDLTGMAMRGVDFKWYDGFFLSMLATSVIIVSINWRRYRLCAHPLHIWIVV
DYTTVFVFRLLMFLDNGLAAGMGLDLGWQQRYTRFCGRILVLSVLVLLLYPFLWVWTVIG
TLWFNSARSCLPEEGQKWGFLIWLLFSYCGLACIACVAVGKWLNRRHALQLRAQQGIPVS
EYGVLVDMIRVPDWAFEAVGLELRGMGQDTAYHPGLYLTTAQREAVEALIQELPKFMLKA
VPTDCSECPICLEEFKVGNEVRGLPCAHNFHVECIDQWLRLNVKCPRCRCSVFPNLDLSA
LNGIRSSSEMLQQDRPSGSSVGEVAATANRYVGPQPAAGRSYLVRLQGLLLRPVVGHHDG
GVSVDSEGGRAVAAEVGSGVVVVVDDGHELRDR
>HORVU1Hr1G000020.4 HORVU1Hr1G000020|chr1H:47115-50750|HC_G|Peroxisomal membrane protein PEX14|none|PF04695|IPR006785
```

**GOMAP step that crashed (if applicable)**
aggregate

**Attach the output files**
```
Error in setnames(x, value) : 
  Can't assign 17 names to a 19 column data.table
Calls: filter_mixed_gaf ... colnames<- -> names<- -> names<-.data.table -> setnames
Execution halted
Running Aggregate Step
Traceback (most recent call last):
  File "./gomap.py", line 103, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 30, in aggregate
    filter_mixed(config)
  File "/opt/GOMAP/code/pipeline/mixed2gaf.py", line 12, in filter_mixed
    check_output_and_run("test.pod",command)
  File "/opt/GOMAP/code/utils/basic_utils.py", line 23, in check_output_and_run
    subprocess.check_call(command,stdin=stdin_file,stdout=stdout_file)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', 'code/pipeline/filter_mixed.r', '/workdir/barley_MNA/GOMAP-160517_barley_NEW_MNA/160517_barley_NEW_MNA.all.yml']' returned non-zero exit status 1
```

**Intermediate outpul file (if applicable)**
-

**System Details**
condo

**Additional context**
/work/dillpicl/cfy/GOMAP-singularity/barley_MNA

**Comment by wkpalan** [comment]
Please remove GOMAP-[barley_MNA]/gaf/mixed-method/[barley_MNA]-fanngo.gaf and run the aggregate step again. Some old files from previous runs have not been cleaned out for the new files to be written.

**Comment by wkpalan** [comment]
Please close this bug if this resolves the issue

**Comment by CFYanarella** [comment]
I removed the GOMAP-[barley_MNA]/gaf/mixed-method/[barley_MNA]-fanngo.gaf and reran the aggregate and it failed again. Upon inspection of the files in GOMAP-[barley_MNA]/gaf/mixed-method/[barley_MNA], the 160517_barley_NEW_MNA.fanngo.gaf file does not appear to have the same information as the other two files.

```
head 160517_barley_NEW_MNA.pannzer.gaf 
!gaf-version:2.0
!db	db_object_id	db_object_symbol	qualifier	term_accession	db_reference	evidence_code	with	aspect	db_object_name	db_object_synonym	db_object_type	taxon	date	assigned_by	annotation_extension	gene_product_form_id
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0000302	MG:0000	IEA	0.584866358296837	P			protein	taxon:4513	02182019	PANNZER		
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0042221	MG:0000	IEA	0.586475693835751	P			protein	taxon:4513	02182019	PANNZER		
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0016881	MG:0000	IEA	0.622681254765478	F			protein	taxon:4513	02182019	PANNZER	
```	

```
head 160517_barley_NEW_MNA.argot2.5.gaf 
!gaf-version:2.0
!db	db_object_id	db_object_symbol	qualifier	term_accession	db_reference	evidence_code	with	aspect	db_object_name	db_object_synonym	db_object_type	taxon	date	assigned_by	annotation_extension	gene_product_form_id
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0004842	MG:0000	IEA	0.147589156790302	F			protein	taxon:4513	02182019	Argot2		
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0008270	MG:0000	IEA	0.76066055806594	F			protein	taxon:4513	02182019	Argot2		
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010.3		GO:0046872	MG:0000	IEA	0.76605797567527	F			protein	taxon:4513	02182019	Argot2	
```

```
head 160517_barley_NEW_MNA.fanngo.gaf 
!gaf-version:2.0
!db	db_object_id	db_object_symbol	qualifier	term_accession	db_reference	evidence_code	with	aspect	db_object_name	db_object_synonym	db_object_type	taxon	date	assigned_by	annotation_extension	gene_product_form_id
maize-GAMER	HORVU1Hr1G000010.3	HORVU1Hr1G000010|chr1H:41961-45310|HC_G|RING-H2	HORVU1Hr1G000010.3	HORVU1Hr1G000010|chr1H:41961-45310|HC_G|RING-H2		GO:0004871	MG:0000	IEA	0.0126555620927263	F			protein	taxon:4513	02212019	FANN-GO		
maize-GAMER	HORVU1Hr1G000020.4	HORVU1Hr1G000020|chr1H:47115-50750|HC_G|Peroxisomal	HORVU1Hr1G000020.4	HORVU1Hr1G000020|chr1H:47115-50750|HC_G|Peroxisomal		GO:0004871	MG:0000	IEA	0.0125919243560479	F			protein	taxon:4513	02212019	FANN-GO		
maize-GAMER	HORVU1Hr1G000030.2	HORVU1Hr1G000030|chr1H:50869-52927|HC_U|unknown	HORVU1Hr1G000030.2	HORVU1Hr1G000030|chr1H:50869-52927|HC_U|unknown		GO:0004871	MG:0000	IEA	0.023433349547238	F			protein	taxon:4513	02212019	FANN-GO	
```

The first section in the description of the sequences, are added in the 160517_barley_NEW_MNA.fanngo.gaf file and not in the 160517_barley_NEW_MNA.pannzer.gaf and 160517_barley_NEW_MNA.argot2.5.gaf files.

**Comment by wkpalan** [comment]
I might have forgotten to mention to remove some files before running the
fanngo step.

Please remove all files from
GOMAP-[barley_MNA]/tmp/mixed-method/fanngo/

Then run fanngo step and then aggregate step
