### ISSUE TITLE
I can't submit data to Argot2.5 (Step number 6 error (mixmeth))

### ISSUE THREAD

**Issue by mmtohm** [Dill-PICL/GOMAP-singularity#30]
Hi, I ran this command "./run-GOMAP-SINGLE.sh --step=mixmeth --config=min-config.yml" on PBS script
and error file show this :

INFO:    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "./gomap.py", line 95, in <module>
    run_mixmeth(config)
  File "/opt/GOMAP/code/gomap_mixmeth.py", line 31, in run_mixmeth
    submit_argot2(config)
  File "/opt/GOMAP/code/pipeline/run_argot2.py", line 176, in submit_argot2
    r_insert = s.post(argot_url,data=payload,files=files,headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
INFO:    Cleaning up image...

How to fix it?

**Comment by mmtohm** [comment]
@wkpalan @Thyra 
I need your help

**Comment by mthang** [comment]
@mmtohm 
I am curious if you got this issue resolved? I am running into this error "failed to establish a new connection" in step 6 as well. I am not sure if it was the issue of the institution firewall issue. Thanks.

**Comment by wkpalan** [comment]
@mmtohm,

Can you send the content of your input config file? Are you able to access https://www.medcomp.medicina.unipd.it/Argot2-5/form_batch.php from your institution?
