### ISSUE TITLE
GOMAP-singularity: IndexError (Aggregate step)

### ISSUE THREAD

**Issue by mmtohm** [Dill-PICL/GOMAP-singularity#31]
Hi, I ran this command "./run-GOMAP-SINGLE.sh --step=aggregate --config=min-config.yml"
and text error show this:

Running Aggregate Step
Traceback (most recent call last):
  File "./gomap.py", line 105, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 24, in aggregate
    download_argot2(config)
  File "/opt/GOMAP/code/pipeline/run_argot2.py", line 201, in download_argot2
    csv_href = argot_config["baseurl"]+"/"+[ link.attrib["href"] for link in all_links if "getTSVFile.php" in link.attrib["href"] ][0]
IndexError: list index out of range

Someone help me please

**Comment by wkpalan** [comment]
@mmtohm,

The GOMAP pipeline cannot run without the output files from Argot2.5 step that are  created in the mixmeth step. Have you been able to run mixmeth step without any errors?
