### ISSUE TITLE
Aggregate error - only a.mm_gaf/ and argot2.5 in b.raw_gaf/ generated

### ISSUE THREAD

**Issue by mwslawinska** [Dill-PICL/GOMAP-singularity#34]
**Describe the bug**
Aggregate step works until generating the files for b.raw_gaf/ folder, error message below. In a.mm_gaf/, there are argot2.5.gaf, fanngo.gaf and pannzer.gaf files, similar to what is there for test.

**Input File**
Cre18.g802155_4532.1.p pacid=52508487 transcript=Cre18.g802155_4532.1 locus=Cre18.g802155_4532 ID=Cre18.g802155_4532.1.v6.1 annot-version=v6.1 assoLoc=4532_18_91121_TE org=Chlamydomonas.reinhardtii.CC-4532
MCHLWEWDADIVILTETKLGPRTRWLKDCLRLENLAYRTITSTKPGTEHYKRRSAGVLMAVSARYHAGGHLHIPPTPPNLLGHLAHCTIRTPHSIPLHILGVYCPEDMPTRRRIYTYCTSTLKSAAAAGEHVLIGGDFNAVLTAADRTGPLDDADRHHARFVSSHRLQRITEPNGTTSMTYYQARDGHPKAISRIDDILICQHTSNALVAAATEPGGNTPTLKVQPSGGLFDHSSVHIHLPTFPMRLWTAPTGNRTGSTTQPPTGPWPQVVLPIPTSTLEAVRTKIEHTLASPIARLAAALQPASTAIRDQVDRYTTGATNATELDTQLRRDPTVQAPNLDALAEQLHDILKDGLNILVDMCPKKPPRTGAFAPRRISKKIRRAHEELRQLRAAIADNDTLHT
Cre18.g802156_4532.1.p pacid=52508488 transcript=Cre18.g802156_4532.1 locus=Cre18.g802156_4532 ID=Cre18.g802156_4532.1.v6.1 annot-version=v6.1 assoLoc=4532_18_91136_TE org=Chlamydomonas.reinhardtii.CC-4532
MAIGAILAALCLPALLRQTANITRHVTATAWHRRHLLLWGAALALTLHSLYLNIPDPCSVEKPHMAILGPTVATSLLSANQTKSLLLAHVPHQPHAAHYVKPTLRGALTIGPAAQPAQASMHTRAPTALHWPPNSNNTYREPQRQHFCSVHALNNSLGLAWLDPLDVLSYAKRVHAHLTATQDPNALFWKDCYCPNSGAFSELLLNHYLYHNATISNIFAYPNRKLIMRRTHFPRLNGDISKEKVLENLPVAARTRGFTVHQYTVRHTIAVRYEAGQWRVIDSVNSPIHNTVLHDNTWNTLDGEVWCLDADMQTRKAIYTYCQQVVGRADACGHHLVTAGDFNAVARAHERDSPIDTADRAHQRFLADSGLRPIRGDTTTTAEWSYEQSRPGMAPYHSRIDDILLCPATRAACTEAREYTSTVAGNFDHKPVHAELLAADLQLWPAPQAGARNPAPQQQTQQRWAEVALPVTQKQLAAAAIRLEEALVEATADLHSATRQATQSIEHALTRHSMDPTGYPASVMHRDLAQDTSIQKADINQLAEQLASALDTGLTCLLEECTRKAPFTGKHHTSRSTARALPEVDAANAAAKLRNEIKACQAEHRQLVADRAKAQREAAATALQHTLATRPAQGHKRIFQKEDMERGLPAVRNPETGEVTTDSTSILAILETHFRKLSAPPRGTRTGDFRLPSNATRGYPFEKADATDQFTLDRNRHPDTHSMLPSMADTANFEQCISHLSRNKATGPDGIPNELLRILPSGMKRNLHCILQIMYVKSQIPETWAASETVLLPKPGDALDIKNKRPIALANTCYKLYTSMLTLGIGELAGPLQLFSEAQEGFRAYCNTERQVLNLVHALEDAALFGKDVYAVYVDYSSAFNTIDQDRLLQIMFDLGLPTDLIRAVRNLYAHATTRIRTEHGSTSAIPIERGTVQGDTLSPVLFILFMEPLVRWLHAGGRGYHYGCLTPSENLQYHCSAAAYADDLAALTNSLDDLQVQCDKIASYAEWASLRVNHTKCATTAIWHDKSRSDPNLDGPTGKATLAAMRRNMTNTIKIGTTPVPYFPPTQPSKYLGV

**GOMAP step that crashed (if applicable)**
aggregate

**Attach the output files**
/tmp:/tmp,/biodata/dep_psl/grp_rgo/slawinska/chlamy_GOextension/GOMAP:/workdir,/netscratch/dep_psl/grp_rgo/slawinska/scratch:/tmpdir,
Running GOMAP --step=aggregate --config=./config.yml
INFO:    Convert SIF file to sandbox...
[1] "Reading the input file"
[1] "Converting to GAF 2.0"
[1] "Checking if data/data/go/go.obo.data exists"
[1] "data/data/go/go.obo.data exists so loading R object"
   user  system elapsed
  3.775   0.178   4.034
[1] "Writing the outfile"
[1] "Reading the input file"
[1] "Converting to GAF 2.0"
[1] "Checking if data/data/go/go.obo.data exists"
[1] "data/data/go/go.obo.data exists so loading R object"
   user  system elapsed
  2.265   0.061   2.326
Warning messages:
1: In min(gaf_data$with) : no non-missing arguments to min; returning Inf
2: In magaf_data$with) : no non-missing arguments to max; returning -Inf
3: In `[.data.table`(gaf_data, , `:=`(aspect, unlist(tmp_aspect))) :
  Column 'aspect' does not exist to remove
[1] "/workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/gaf/a.mm_gaf/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.fanngo.gaf"
[1] "Reading the input file"
[1] "Converting to GAF 2.0"
[1] "Checking if data/data/go/go.obo.data exists"
[1] "data/data/go/go.obo.data exists so loading R object"
   user  system elapsed
  3.659   0.021   3.681

       F        P
 [6082264 31613628](callto:6082264 31613628)
[1] "Writing FANNGO gaf "
$baseurl
[1] "http://www.medcomp.medicina.unipd.it/Argot2-5/"

$batch_url
[1] "http://www.medcomp.medicina.unipd.it/Argot2-5/insert_batch.php"

$payload
$payload$blast_file
[1] "None"

$payload$descr
[1] "None"

$payload$email
[1] "None"

$payload$filtra
[1] "checked"

$payload$hmmer_file
[1] "None"

$payload$inf_content
[1] "0"

$payload$int_confidence
[1] "0"

$payload$measure
[1] "simgic"

$payload$rule_system
[1] "both"

$payload$tax_id
[1] "None"

$payload$totalScore
[1] "0"

$payload$w_hypoth
[1] "open_world"

$preprocess
$preprocess$blast
[1] "tmp/mixed-meth/argot2.5/blast"

$preprocess$hmmer
[1] "tmp/mixed-meth/argot2.5/hmmer"

$preprocess$html
[1] "tmp/mixed-meth/argot2.5/html"

$result_dir
[1] "tmp/mixed-meth/argot2.5/results"

$score_th
$score_th$C
[1] 0.05

$score_th$F
[1] 0.15

$score_th$P
[1] 0.15

There were 17 warnings (use warnings() to see them)
Error in fread(infile, skip = comment_lines, header = F, stringsAsFactors = F,  :
  skip=2 but the input only has 2 lines
Calls: filter_mixed_gaf -> read_gaf -> fread
Execution halted
Running Aggregate Step
Traceback (most recent call last):
  File "./gomap.py", line 103, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 30, in aggregate
    filter_mixed(config)
  File "/opt/GOMAP/code/pipeline/mixed2gaf.py", line 12, in filter_mixed
    check_output_and_run("test.pod",command)
  File "/opt/GOMAP/code/utils/basic_utils.py", line 24, in check_output_and_run
    subprocess.check_call(command,stdin=stdin_file,stdout=stdout_file)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', 'code/pipeline/filter_mixed.r', '/workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.all.yml']' returned non-zero exit status 1
INFO:    Cleaning up image...
**Intermediate outpul file (if applicable)**
The first 10 lines of the the intermediate output file that was created last by GOMAP

**System Details**
OS: Ubuntu
Version: 4.15.0-88-generic #88-Ubuntu x86_64
Memory Size: 64GB

**Additional context**

**Comment by mwslawinska** [comment]
Update: somehow, files in b. got generated, but then the script stops at generating the files in c.uniq_gaf/ with the following message: The output (if any) follows:

/tmp:/tmp,/biodata/dep_psl/grp_rgo/slawinska/chlamy_GOextension/GOMAP:/workdir,/netscratch/dep_psl/grp_rgo/slawinska/scratch:/tmpdir,
Running GOMAP --step=aggregate --config=./config.yml
INFO:    Convert SIF file to sandbox...
[1] "/workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/gaf/a.mm_gaf/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.fanngo.gaf"
Error in fread(infile, skip = comment_lines, header = F, stringsAsFactors = F,  :
  skip=2 but the input only has 2 lines
Calls: filter_mixed_gaf -> read_gaf -> fread
Execution halted
Running Aggregate Step
Traceback (most recent call last):
  File "./gomap.py", line 103, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 30, in aggregate
    filter_mixed(config)
  File "/opt/GOMAP/code/pipeline/mixed2gaf.py", line 12, in filter_mixed
    check_output_and_run("test.pod",command)
  File "/opt/GOMAP/code/utils/basic_utils.py", line 24, in check_output_and_run
    subprocess.check_call(command,stdin=stdin_file,stdout=stdout_file)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', 'code/pipeline/filter_mixed.r', '/workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.all.yml']' returned non-zero exit status 1
INFO:    Cleaning up image...

The beggining of the file /workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/gaf/a.mm_gaf/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.fanngo.gaf looks like:
!gaf-version:2.0
!db db_object_id    db_object_symbol    qualifier   term_accession  db_reference    evidence_code   with    aspect  db_object_name  db_object_synonym   db_object_type  taxon   date    assigned_by annotation_extension    gene_product_form_id
GOMAP   Cre18.g802155_4532.1.p  Cre18.g802155_4532.1.p      GO:0004871  GOMAP:0000  IEA 0.0433069696507035  F           gene    taxon:3055  20230428    FANN-GO
GOMAP   Cre18.g802156_4532.1.p  Cre18.g802156_4532.1.p      GO:0004871  GOMAP:0000  IEA 0.0126777801754226  F           gene    taxon:3055  20230428    FANN-GO
GOMAP   Cre03.g198700_4532.1.p  Cre03.g198700_4532.1.p      GO:0004871  GOMAP:0000  IEA 0.0157637060255612  F           gene    taxon:3055  20230428    FANN-GO

I tried re-running the aggregate step after deleting the gaf files but it didn't help. Any idea how to fix that?

**Comment by mwslawinska** [comment]
Running the mixmeth step again solved the issue (new Pannzer results were generated and then no problems with mixed methods were no longer encountered, however, no Interproscan, arabidopsis (TAIR) and uniprot .gaf files were generated (I'll create a new issue).
